//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEETS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livre
    {
        public Livre()
        {
            this.Offres = new HashSet<Offre>();
        }
    
        public int Id { get; set; }
        public string CodeISBN_10 { get; set; }
        public string Nom { get; set; }
        public string Image { get; set; }
        public string Auteur { get; set; }
        public string DescriptLivre { get; set; }
        public string SousTitre { get; set; }
        public string Image2 { get; set; }
        public string CodeISBN_13 { get; set; }
    
        public virtual Livre_Cours_TypeReferences Livre_Cours_TypeReferences { get; set; }
        public virtual ICollection<Offre> Offres { get; set; }
    }
}
