//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEETS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profil
    {
        public Profil()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.AspNetUsers1 = new HashSet<AspNetUser>();
        }
    
        public string CodeProfil { get; set; }
        public string DescProfil { get; set; }
    
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers1 { get; set; }
    }
}
