@startuml
skinparam style strictuml
hide methods
hide empty members
title Modèle du domaine \n(Plateforme d’échange d’articles scolaires)
class Utilisateur {
  nom : String
  courriel : Courriel
}

class  "Étudiant"  as E
class E {
}

class "Administrateur " as A 
class A {
  
}

class "Compte\nGoogle" as Compte {
}

class Article {
  nom : String
}

class Livre {
  codeISBN : ISBN
  /imageCouverture : Image
}
class NotesDeCours {
  dateEdition : String
}
class Calculatrice {
  modele : String
  OS : String
}


class Offre{
  dateDébut
  prix
  condition : Condition
}


A .up.|> Utilisateur
E .up.|> Utilisateur
Livre .up.|> Article
NotesDeCours .up.|> Article
Calculatrice .up.|> Article
Utilisateur "1" - "1" Compte: s'authentifie-par >

E "1" -- "1..*" Offre: crée >
'E "0..*" - "1..*" Offre: Misé >
'E "0..*" - "1..*" Article: recherche >
Offre "*" - "1" Article : propose >
A "1..*" - "0..*" Offre : modifie >
@enduml
