@startuml
title Plateforme d'échange d'articles scolaires
left to right direction
skinparam style strictuml
skinparam packageStyle rect
actor Administrateur
actor Étudiant
actor Modérateur
rectangle "<<actor>>\nService\nd'authentification\n(Google)" as SA
rectangle "Plateforme d'échange\nd'articles scolaires (PÉÉTS)" {
  (Gérer un compte) as GC
  (Ajouter une offre\npour un livre) as AOL #lightblue
  (Ajouter une offre\npour une calculatrice) as AOC #lightgreen
  (Ajouter une offre\npour des notes de cours) as AON #lightgreen
  (Modifier une offre) as MO #lightblue
  (Consulter une offre) as CO #lightblue
  (Envoyer un message\nà propos d'une offre) as EM #lightgreen
  (Imprimer une étiquette) as IE #lightgreen
  Étudiant -- GC
  GC -- SA
  Étudiant -- AOL
  Étudiant -- AON
  Étudiant -- AOC
  Étudiant -- MO
  Étudiant -- (Fermer une offre) 
  Étudiant -- (Rechercher un article)
  Étudiant -- CO
  Étudiant -- EM
  Administrateur -- MO
  Administrateur -- (Fermer une offre)
  Administrateur -- IE
  Administrateur -- EM
}
'légende, expliquer les couleurs
(//Nouvelle//\n//fonctionnalité//) as nf #lightgreen
(//Fonctionnalité//\n//modifiée//) as fm #lightblue
(//Fonctionnalité//\n//existante//) as fe
'forcer une mise en page avec les lignes cachées
nf -[#transparent]right- fm
fm -[#transparent]right- fe
fe -[#transparent]right- SA
note as N1
 En utilisant les comptes Google, 
 la gestion de comptes est plus
 facile à implémenter
end note
SA . N1
@enduml
