@startuml
title Plateforme d'échange d'articles scolaires
left to right direction
skinparam style strictuml
skinparam packageStyle rect
actor Administrator
actor Étudiant
actor Modérateur
rectangle "<<actor>>\nService\nd'authentification\n(Google)" as SA
rectangle "Plateforme d'échange\nd'articles scolaires (PÉÉTS)" {
  Étudiant -- (Gérer compte)
  (Gérer compte) -- SA
  Étudiant -- (Gérer offres)
  Étudiant -- (Rechercher article)
  Étudiant -- (Consulter offre)
  Étudiant -- (Envoyer un message à propos d'une offre)
  Administrator -- (Gérer offres)
  Administrator -- (Imprimer une étiquette)
  Administrator -- (Envoyer un message à propos d'une offre)
}
note as N1
 En utilisant les comptes Google, 
 la gestion de comptes est plus
 facile à implémenter
end note
SA . N1
@enduml
