//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEETS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public Cours()
        {
            this.Livre_Cours_TypeReferences = new HashSet<Livre_Cours_TypeReferences>();
        }
    
        public string Sigle { get; set; }
        public string NomCours { get; set; }
    
        public virtual ICollection<Livre_Cours_TypeReferences> Livre_Cours_TypeReferences { get; set; }
    }
}
