//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEETS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etat
    {
        public Etat()
        {
            this.Offres = new HashSet<Offre>();
        }
    
        public string CodeEtat { get; set; }
        public string DesctEtat { get; set; }
    
        public virtual ICollection<Offre> Offres { get; set; }
    }
}
